services:
#mariadb
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env 
    secrets:
      - db_name
      - db_password
      - db_user
      - db_root_password
    networks :
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

#nginx
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

#wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    secrets :
      - db_user
      - db_password
      - wp_admin_password
      - wp_admin_user
    networks:
      - inception
    restart: always

# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vdeliere/data/mariadb
      
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vdeliere/data/wordpress
      

# the networks part
networks:
  inception:
    name: inception

# the secrets part
secrets:
  db_name:
    file: ../secrets/db_name.txt
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt